server:
  port: 8081
  servlet:
    context-path: /AdminPortal
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/ead_5
    username: root
    password: 12345
    driver-class-name : com.mysql.cj.jdbc.Driver
  mvc:
   view:
    prefix: /WEB-INF/pages/
    suffix: .jsp